bangazonworkforcemgt/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from hrapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hrapp.urls'))
]

hrapp/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name = 'hrapp'

urlpatterns = [
    path('', home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_user, name='logout'),
    path('employees/', employee_list, name='employee_list'),
    path('employees/<int:employee_id>/', employee_details, name='employee'),
    path('employees/employee_form', employee_form, name='employee_form'),
    path('employees/<int:employee_id>/employee_form/',
         employee_edit_form, name='employee_edit_form'),
    path('departments/form', department_form, name='department_form'),
    path('departments/<int:department_id>',
         department_details, name='department'),
    path('departments/', department_list, name='department_list'),
    path('trainings', training_program_list, name='training_program_list'),
    path('trainings/past', training_program_past, name='training_program_past'),
    path('trainings/<int:training_program_id>/',
         training_program_details, name='training_program'),
    path('trainings/training_form', training_form, name='training_form'),
    path('trainings/<int:training_program_id>/form/',
         training_edit_form, name="training_edit_form"),
    path('computers/form', computer_form, name='computer_form'),
    path('computers/', computer_list, name='computer_list'),
    path('computers/<int:computer_id>/', computer_details, name='computer')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hrapp/models/computer.py
from django.db import models
from django.urls import reverse


class Computer(models.Model):
    '''
    description: This class creates a computer and its properties
    author: Joe Shep
    properties:
      make: The make will contain the name of the brand of the computer.
      purchase_date: This property contains the purchase date in string form.
      decomission_date: This property contains the dicomission date in string form.
      employees: This property contains the many to many relationship with the computer/employee model
    '''
    manufacturer = models.CharField(null=True, max_length=50)
    make = models.CharField(max_length=20)
    purchase_date = models.DateField()
    decommission_date = models.DateField(null=True, blank=True, default=None)
    # employees = models.ManyToManyField("Employee", through='EmployeeComputer')

    class Meta:
        verbose_name = ("Computer")
        verbose_name_plural = ("Computers")

    def get_absolute_url(self):
        return reverse("Computer_detail", kwargs={"pk": self.pk})

hrapp/models/departments.py
from django.db import models
# from django.urls import reverse


class Department(models.Model):

    department_name = models.CharField(max_length=100)
    department_budget = models.FloatField()

    class Meta:
        verbose_name = ("Department")
        verbose_name_plural = ("Departments")

    def __str__(self):
        return f"{self.department_name} {self.department_budget}"

    # def get_absolute_url(self):
    #     return reverse("Department_detail", kwargs={"pk": self.pk})

hrapp/models/employee.py
from django.db import models
from django.urls import reverse
from .departments import Department


class Employee(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    start_date = models.DateField()
    is_supervisor = models.BooleanField()
    department = models.ForeignKey(Department,
                                   related_name="Department",
                                   null=True,  # Makes column nullable in DB
                                   blank=True,  # Allows blank value on objects
                                   on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("Employee")
        verbose_name_plural = ("Employees")
        
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("Employee_detail", kwargs={"pk": self.pk})

hrapp/models/employee_computer.py
from django.db import models
from .employee import Employee
from .computer import Computer


class EmployeeComputer(models.Model):
    """
    Creates the join table for the many to many relationship between computers and employees
    Author: Joe Shep
    methods: none
    """

    employee = models.ForeignKey(Employee,
                                 related_name="EmployeeComputers",
                                 null=True,  # Makes column nullable in DB
                                 blank=True,  # Allows blank value on objects
                                 on_delete=models.CASCADE)
    computer = models.ForeignKey(Computer,
                                 related_name="EmployeesComputer",
                                 null=True,  # Makes column nullable in DB
                                 blank=True,  # Allows blank value on objects
                                 on_delete=models.CASCADE)
    assigned_date = models.DateField(
        null=True, auto_now=False, auto_now_add=False)
    unassigned_date = models.DateField(
        null=True, auto_now=False, auto_now_add=False)

hrapp/models/training_program.py
from django.db import models

class TrainingProgram(models.Model):

    
    training_title = models.CharField(max_length=100)
    start_date = models.DateField(null=True, auto_now=False, auto_now_add=False)
    end_date = models.DateField(null=True, auto_now=False, auto_now_add=False)
    max_capacity = models.IntegerField()
    

    class Meta:
        verbose_name = ("Training Program")
        verbose_name_plural = ("Training Programs")

hrapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

hrapp/templates/computers/computer_details.html
{% extends 'shared/base.html' %} 
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/lists.css' %}" />
{% endblock css %}

{% block content %}

<section class="computer-details">
  <h1>{{ computer.make }}</h1>
  <h2>Pruchased on: {{ computer.purchase_date }}</h2>
  <h2>Decommission on: {{ computer.decommission_date }}</h2>
  <h2>Manufacturer: {{ computer.manufacturer }}</h2>
</section>
{% if user.is_authenticated %}
<form action="{% url 'hrapp:computer' computer.id %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="actual_method" value="DELETE" />
  <button class="button">Delete</button>
</form>
{% endif %} {% endblock %}

hrapp/templates/computers/computer_form.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Bangazon</title>
  </head>
  <body>
    <h1>Computer Form</h1>

    <form action="{% url 'hrapp:computer_list' %}" method="post">
      {% csrf_token %}
      <fieldset>
        <label for="make">Make: </label>
        <input id="make" type="text" name="make" />
      </fieldset>
      <fieldset>
        <label for="purchase_date">Purchase Date: </label>
        <input id="purchase_date" type="date" name="purchase_date" />
      </fieldset>
      <fieldset>
        <label for="decommission_date">Decommission Date: </label>
        <input id="decommission_date" type="date" name="decommission_date" />
      </fieldset>
      <fieldset>
        <label for="manufacturer">Manufacturer: </label>
        <input id="manufacturer" type="text" name="manufacturer" />
      </fieldset>

      <input type="submit" value="Add It" />
    </form>
  </body>
</html>

hrapp/templates/computers/computer_list.html
{% extends 'shared/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/lists.css' %}" />
{% endblock css %}
 {% block content %}
<h1>Computers</h1>
{% if user.is_authenticated %}
  <section style="display:flex;">
    <form action="{% url 'hrapp:computer_form' %}" method="GET">
            {% csrf_token %}
            <button class="button">Add Computer</button>
        </form>
  </section>
{% endif %} 

<ol class="list">
  {% for computer in computers %}
  <li class="card">
    <a class="details-link" class="employee-name" href="{% url 'hrapp:computer' computer.id %}"> {{ computer.make }} </a> 
  </li>
  {% endfor %}
</ol>
{% endblock content %}

hrapp/templates/departments/department_details.html
{% extends 'shared/base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'styles/lists.css'%}" />
{% endblock css %}

{% block content %}

<section class="department-details">
  <h1>{{ department }}</h1>
  <h2>Budget: {{ department.department_budget }}</h2>
  {% for employee in department.employees %}
    <li>{{ employee.first_name }}</li>
  {% endfor %}
</section>
<section style="display:flex;">
    <form action="{% url 'hrapp:department_list' %}" method="GET">
            {% csrf_token %}
            <button class="button">Back to Department List</button>
    </form>

{% endblock %}

hrapp/templates/departments/department_form.html
{% extends 'shared/base.html' %}

{% block content %}
    <h1>Department to be added</h1>


    <form action="{% url 'hrapp:department_list' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="title">Department Name: </label>
          <input id="department_name" type="text" name="department_name">
      </fieldset>
      <fieldset>
          <label for="budget">Budget: </label>
          <input id="department_budget" type="interger" name="department_budget">
      </fieldset>

      <input type="submit" value="Add It" />
    </form>
{% endblock content %}

hrapp/templates/departments/department_list.html
{% extends 'shared/base.html' %} 
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'styles/lists.css'%}" />
{% endblock css %}

{% block content %}

<h1>Departments</h1>
{% if user.is_authenticated %}
  <section style="display:flex;">
    <form action="{% url 'hrapp:department_form' %}" method="GET">
            {% csrf_token %}
            <button class="button">Add Department</button>
        </form>
  </section>
{% endif %} 



<ol class="list">
  {% for department in all_departments %}
    <li class="card">
      <a class="details-link department-name" href="{% url 'hrapp:department' department.id %}">
        <h3 class="deptartment-name">{{ department.department_name }}</h3>
      </a>
      <h3 class="budget">Budget: ${{department.department_budget}}</h3>
      <h5 class="department-size">Employees: {{ department.employees|length }}</h5>
    </li>
  {% endfor %}
</ol>

{% endblock content %}

hrapp/templates/employees/employee_details.html
{% extends 'shared/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/lists.css' %}" />
{% endblock css %}
{% block content %}

  <section class="employee-details">
    <h1>{{ employee.first_name }} {{ employee.last_name }}</h1>
    <h2>{{ employee.department_name }}</h2>
    <p>Start Date: {{ employee.start_date }}</p>
    <p>Supervisor: {{ employee.is_supervisor }}</p>
  </section>

{% if user.is_authenticated %}
  <section id="employee-actions" style="display:flex;">
    <form action="{% url 'hrapp:employee_edit_form' employee.id %}" method="GET">
            {% csrf_token %}
            <button class="button">Edit</button>
        </form>
  </section>
{% endif %}

{% endblock %}

hrapp/templates/employees/employee_form.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    <h1>Employee Form</h1>

    {% if employee.id is not None %}
        <form action="{% url 'hrapp:employee' employee.id %}" method="post">
    {% else %}
        <form action="{% url 'hrapp:employee_list' %}" method="post">
    {% endif %}
      {% csrf_token %}
        <fieldset>
            <label for="first_name">First Name: </label>
            <input id="first_name" type="text" name="first_name" value="{{ employee.first_name }}">
        </fieldset>
        <fieldset>
            <label for="last_name">Last Name: </label>
            <input id="last_name" type="text" name="last_name" value="{{ employee.last_name }}">
        </fieldset>
        <fieldset>
            <label for="start_date">Start Date: </label>
            <input id="start_date" type="date" name="start_date" value="{{ employee.start_date }}">
        </fieldset>
        <fieldset>
          <label for="is_supervisor">Is employee a department supervivsor?</label>
          <select id="is_supervisor" type="text" name="is_supervisor" value="{{ employee.is_supervisor }}">
            <option {%if employee.is_supervisor == "False"%}selected{%endif%} value="False">No</option>
            <option {%if employee.is_supervisor == "True"%}selected{%endif%} value="True">Yes </option>
            </select>
        </fieldset>
        <fieldset>
            <label for="department_id">Department: </label>
            <select id="department_id" type="text" name="department_id">
                    {% for department in all_departments %}
                        <option {% if department.id == employee.department_id %}selected{% endif %} value="{{ department.id }}">{{ department.department_name }}</option>
                    {% endfor %}
            </select>
        </fieldset>

        {% if employee.id is not None %}
            <input type="hidden" name="actual_method" value="PUT">
            <input type="submit" value="Update" />
        {% else %}
            <input type="submit" value="Add It" />
        {% endif %}
        
        </form>
  </body>
</html>

   

hrapp/templates/employees/employees_list.html
{% extends 'shared/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/lists.css' %}" />
{% endblock css %}

{% block content %}
<h1>Employees</h1>
{% if user.is_authenticated %}
  <section style="display:flex;">
    <form action="{% url 'hrapp:employee_form' %}" method="GET">
            {% csrf_token %}
            <button class="button">Add Employee</button>
        </form>
  </section>
{% endif %}

<ol class="employee-list">
<ol class="list">
{% for employee in employees %}
    <li class="card">
        <a class="details-link" href="{% url 'hrapp:employee' employee.id %}">
        <h3 class="employee-name">{{ employee.first_name }} {{ employee.last_name }}</h3></a>
        <h5 class="employee-department">{{ employee.department_name }}</h5>
    </li>
{% endfor %}
</ol>
{% endblock content %}

hrapp/templates/home.html
{% extends 'shared/base.html' %}

{% block content %}
<h1>Welcome to the Bangazon Workforce Management System</h1>
{% endblock content %}

hrapp/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Bangazon Workforce Management</title>

    <link rel="stylesheet" href="{% static 'styles/base.css' %}" />

    {% block css %}
    {% endblock %}
</head>

<body>

    <nav id="site-nav">
        <ol class="nav-list">
            <li class="nav-list__route"><a href="{% url 'hrapp:employee_list' %}">Employees</a></li>
            <li class="nav-list__route"><a href="{% url 'hrapp:department_list' %}">Departments</a></li>
            <li class="nav-list__route"><a href="{% url 'hrapp:computer_list' %}">Computers</a></li>
            <li class="nav-list__route"><a href="{% url 'hrapp:training_program_list' %}">Training Programs</a></li>
            {% if user.is_authenticated %}
            <li class="nav-list__route logout"><a href="{% url 'hrapp:logout' %}">Logout</a></li>
            {% else %}
            <li class="nav-list__route login"><a href="/accounts/login">Login</a></li>
            {% endif %}
        </ol>
    </nav>

    <main class="main-content">
        {% block content %}
        {% endblock %}
    </main>

    {% block scripts %}
    {% endblock scripts %}

</body>

</html>

hrapp/templates/training_programs/training_program_details.html
{% extends 'shared/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/lists.css' %}" />
{% endblock css %}
{% block content %}

  <section class="training_program-details">
    <h1>{{ training_program.training_title }} </h1>
    <p>Start Date: {{ training_program.start_date }}</p>
    <p>End Date: {{ training_program.end_date }}</p>
    <p>Maximum Attendees: {{ training_program.max_capacity }}</p>
  </section>

{% if user.is_authenticated %}
  <section id="training_program-actions" style="display:flex;">
    <form action="{% url 'hrapp:training_edit_form' training_program.id %}" method="GET">
      {% csrf_token %}
      <button class="button">Edit</button>
    </form>
    <form action="{% url 'hrapp:training_program' training_program.id %}" method="POST">
    {% csrf_token %}
        <input type="hidden" name="actual_method" value="DELETE">
        <button class="button">Delete</button>
    </form>
  </section>
{% endif %}

{% endblock %}

hrapp/templates/training_programs/training_program_form.html
{% extends 'shared/base.html' %} 
{% block content %}

{% if training_program.id is not None %}
    <form action="{% url 'hrapp:training_program' training_program.id%}" method="POST">
{% else %}
    <form action="{% url 'hrapp:training_program_list' %}" method="POST">
{% endif %}
    {% csrf_token %}
    <fieldset>
        <label for="training_title">Title: </lable>
        <input id="training_title" type="text" name="training_title" value="{{ training_program.training_title }}">
    </fieldset>
    <fieldset>
        <label for="start_date">Start Date: </label>
        <input id="start_date" type="date" name="start_date" value={{ training_program.start_date }}>
    </fieldset>
    <fieldset>
        <label for="end_date">End Date: </label>
        <input id="end_date" type="date" name="end_date" value={{ training_program.end_date }}>
    </fieldset>
    <fieldset>
        <label for="max_capacity">Max Capacity: </label>
        <input id="max_capacity" type="number" name="max_capacity" value={{ training_program.max_capacity }}>
    </fieldset>

{% if training_program.id is not None %}
    <input type="hidden" name="actual_method" value="PUT">
    <input type="submit" value="Update" />
{% else %}
    <input type="submit" values="Add It" />
{% endif %}
</form>


{% endblock content %}

hrapp/templates/training_programs/training_program_list.html
{% extends 'shared/base.html' %} 
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/lists.css' %}" />
{% endblock css %}

{% block content %}

<h1>Scheduled Training Programs</h1>

{% if user.is_authenticated %}
  <section style="display:flex;">
    <form action="{% url 'hrapp:training_form' %}" method="GET">
            {% csrf_token %}
            <button class="button">Add New Training</button>
        </form>
  </section>
{% endif %} 

<ol class="list">
  {% for training_program in training_programs %}
  <li class="card">
    <a class="details-link" class="employee-name" href="{% url 'hrapp:training_program' training_program.id %}">  
      {{ training_program.training_title }} 
      </a>
    
  </li>
  {% endfor %}
</ol>

  <section style="display:flex;">
    <form action="{% url 'hrapp:training_program_past' %}" method="GET">
            {% csrf_token %}
            <button class="button">See Past Programs</button>
        </form>
  </section>


{% endblock content %}

hrapp/templates/training_programs/training_program_past.html
{% extends 'shared/base.html' %} 
{% block content %}

<h1>Previous Training Programs</h1>


<ol>
  {% for training_program in training_programs %}
  <li>
  
    <h3>{{ training_program.training_title }}</h3>
      
    
   <p> Start Date: {{training_program.start_date}} </p>
   <p>  End Date: {{training_program.end_date}} </p>
   <p>  Maximum Number of Attendees: {{training_program.max_capacity}} </p>
  </li>
  {% endfor %}
</ol>

{% endblock content %}